### ISSUE TITLE
[README.md] Proposal: add screenshots

### ISSUE THREAD

**Issue by Karatuss** [SeoulSKY/PingPong#1]
Hi, @SeoulSKY.

Can you add some `in-game screenshots` for players? If you add them, users who consider playing your ping pong game might feel interested in it.

This is just a suggestion for you, so this is a perfectly duty-free issue! 😋

**Comment by SeoulSKY** [comment]
> Hi, @SeoulSKY.
> 
> Can you add some `in-game screenshots` for players? If you add them, users who consider playing your ping pong game might feel interested in it.
> 
> This is just a suggestion for you, so this is a perfectly duty-free issue! 😋

Good idea! Thank you for the suggestion!
